# Generated by Django 4.2.19 on 2025-02-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='ean',
            field=models.CharField(blank=True, max_length=40, verbose_name='EAN'),
        ),
    ]
