# Generated by Django 4.2.18 on 2025-02-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_amount_override',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
