# Generated by Django 4.2.20 on 2025-04-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_cached',
            field=models.IntegerField(default=0),
        ),
    ]
