# Generated by Django 4.2.19 on 2025-02-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rescanned',
            field=models.BooleanField(default=False),
        ),
    ]
