# Generated by Django 4.2.19 on 2025-02-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_rename_stock_position_group'),
        ('box', '0003_box_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='position.position'),
        ),
    ]
