# Generated by Django 4.2.20 on 2025-03-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotassistantthread',
            name='stat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
