# Generated by Django 4.2.20 on 2025-04-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatbotassistantthread_model_delete_fastprompts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotassistantthread',
            name='model',
            field=models.CharField(blank=True, choices=[('azure', 'Azure'), ('opeanai', 'Opeanai')], default='opeanai', max_length=50, null=True),
        ),
    ]
