# Generated by Django 4.2.19 on 2025-02-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_alter_box_depth_alter_box_height_alter_box_weight_and_more'),
        ('group', '0002_group_rescanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='box.box'),
        ),
    ]
