# Generated by Django 4.2.19 on 2025-02-18 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_created_at'),
        ('group', '0001_initial'),
        ('position', '0005_position_warehouse'),
        ('operation', '0006_remove_operation_invoice_delivery_places_gln_and_more'),
        ('batch', '0002_remove_batch_quantity'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='batch.batch'),
        ),
        migrations.AddField(
            model_name='history',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='group.group'),
        ),
        migrations.AddField(
            model_name='history',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='position.position'),
        ),
        migrations.AddField(
            model_name='history',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='product.product'),
        ),
        migrations.AlterField(
            model_name='history',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='operation.operation'),
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
