# Generated by Django 4.2.19 on 2025-02-24 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0004_alter_history_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='history',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='history',
            name='group',
        ),
        migrations.RemoveField(
            model_name='history',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='history',
            name='position',
        ),
        migrations.RemoveField(
            model_name='history',
            name='product',
        ),
        migrations.AddField(
            model_name='history',
            name='related_id',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='type',
            field=models.CharField(choices=[('operation', 'Operace'), ('product', 'Produkt'), ('batch', 'Šarže'), ('group', 'Skupina'), ('position', 'Pozice')], max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['type'], name='history_his_type_fb2bba_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['timestamp'], name='history_his_timesta_1d8a61_idx'),
        ),
    ]
