# Generated by Django 4.2.19 on 2025-02-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('operation', '0004_operation_cash_on_delivery_operation_delivery_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client'),
            preserve_default=False,
        ),
    ]
