# Generated by Django 4.2.20 on 2025-03-26 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardconfig',
            name='type',
            field=models.CharField(choices=[('main', 'Hlavní dashboard'), ('stats', 'Statistiky')], default='main', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdashboardconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userdashboardconfig',
            unique_together={('user', 'type')},
        ),
    ]
