# Generated by Django 4.2.19 on 2025-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_rename_timestamp_operation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
