# Generated by Django 4.2.19 on 2025-02-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_operation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cash_on_delivery',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cash on delivery'),
        ),
        migrations.AddField(
            model_name='operation',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Delivery city'),
        ),
        migrations.AddField(
            model_name='operation',
            name='delivery_country',
            field=models.CharField(blank=True, default='CZ', max_length=80, null=True, verbose_name='Delivery country'),
        ),
        migrations.AddField(
            model_name='operation',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery date'),
        ),
        migrations.AddField(
            model_name='operation',
            name='delivery_email',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Delivery email'),
        ),
        migrations.AddField(
            model_name='operation',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Delivery name'),
        ),
        migrations.AddField(
            model_name='operation',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Delivery note'),
        ),
        migrations.AddField(
            model_name='operation',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Delivery phone'),
        ),
        migrations.AddField(
            model_name='operation',
            name='delivery_psc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Delivery zip code'),
        ),
        migrations.AddField(
            model_name='operation',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Delivery street'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_city',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Invoice city'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_country',
            field=models.CharField(blank=True, default='CZ', max_length=80, null=True, verbose_name='Invoice country'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_delivery_places_gln',
            field=models.CharField(blank=True, default='', max_length=17, verbose_name='Delivery Place GS1 Global Location Number'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_email',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Invoice email'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_gln',
            field=models.CharField(blank=True, max_length=18, verbose_name='Invoice GS1 Global Location Number'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_ico',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IC'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Invoice name'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_phone',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Invoice phone'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_psc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Invoice zip code'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_street',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Invoice street'),
        ),
        migrations.AddField(
            model_name='operation',
            name='invoice_vat',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VAT number'),
        ),
        migrations.AddField(
            model_name='operation',
            name='shipping_extern_id',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Parcel shop ID'),
        ),
        migrations.AddField(
            model_name='operation',
            name='shipping_note',
            field=models.TextField(blank=True, max_length=550, null=True, verbose_name='Shipping note'),
        ),
    ]
