# Generated by Django 4.2.19 on 2025-02-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_operation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='invoice_delivery_places_gln',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='invoice_gln',
        ),
    ]
