# Generated by Django 4.2.20 on 2025-03-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_remove_operation_invoice_delivery_places_gln_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Vytvořeno'), ('IN_PROGRESS', 'Probíhá'), ('COMPLETED', 'Dokončeno'), ('CANCELLED', 'Zrušeno'), ('BOX', 'Balení')], default='CREATED', max_length=15),
        ),
    ]
