# Generated by Django 4.2.20 on 2025-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_alter_operation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Vytvořeno'), ('COMPLETED', 'Dokončeno'), ('CANCELLED', 'Zrušeno'), ('BOX', 'Balení')], default='CREATED', max_length=15),
        ),
    ]
