# Generated by Django 4.2.20 on 2025-03-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_alter_operation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='shipping_extern_id',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='shipping_note',
        ),
    ]
