# Generated by Django 4.2.17 on 2025-01-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('client', '0001_initial'),
        ('client_role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='client.client')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='client_role.clientrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_roles', to='user.user')),
            ],
        ),
    ]
