# Generated by Django 4.2.17 on 2025-01-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='stock',
            new_name='group',
        ),
    ]
