# Generated by Django 4.2.19 on 2025-02-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('position', '0002_rename_stock_position_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='group.group'),
        ),
    ]
