"""
Django settings for StockWise project.

Generated by 'django-admin startproject' using Django 4.2.17.
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Načtení proměnných z .env souboru
load_dotenv()

# Klíč pro přístup k OpenAI a model
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL = os.getenv("OPENAI_MODEL")

# NEPOUŽÍVEJTE TOTO V PRODUKCI BEZ ÚPRAV
SECRET_KEY = 'django-insecure-994v!x)5h7$gy&$61bo(qsc&*8s%6nv%bzexsr!k!4k3)r*63v'
DEBUG = True
ALLOWED_HOSTS = ['*']  # Otevřeno pro všechny – vhodné pouze pro vývoj

# Seznam Django a vlastních aplikací
INSTALLED_APPS = [
    "corsheaders",
    'drf_yasg',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Vlastní aplikace
    'product',
    'user',
    'warehouse',
    'batch',
    'box',
    'client',
    'group',
    'history',
    'operation',
    'position',
    'dashboard',
    'chatbot'
]

# Konfigurace Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # JSON výstup jako výchozí
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'StockWise.middleware.CookieJWTAuthentication',  # Vlastní cookie auth
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Všude je potřeba auth
    ],
    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 10
}

# Konfigurace JWT tokenů
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Middleware včetně CORS a počítadla dotazů
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'querycount.middleware.QueryCountMiddleware'
]

# CORS a CSRF nastavení pro FE běžící na localhostu nebo Vercelu
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://stock-wise-fe.vercel.app"
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://stock-wise-fe.vercel.app"
]

CORS_ALLOW_CREDENTIALS = True

# Nastavení cookies pro bezpečné přihlášení
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'StockWise.urls'

# Templating engine
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StockWise.wsgi.application'

# Databáze – výchozí Supabase
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.etcoksjerwplaibvjtjt',
        'PASSWORD': 'Noidlevinedowney12+',
        'HOST': 'aws-0-eu-west-2.pooler.supabase.com',
        'PORT': '5432',
    }
}

# Testovací databáze (Docker/Supabase lokálně)
#if 'test' in sys.argv or os.getenv('TESTING') == '1':
#   DATABASES['default'] = {
#      'ENGINE': 'django.db.backends.postgresql',
#      'NAME': 'stockwise_test',
#      'USER': 'postgres',
#      'PASSWORD': 'postgres',
#      'HOST': 'postgres',
#      'PORT': '5432',
#   }

# Validace hesla
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Custom user model
AUTH_USER_MODEL = 'user.User'

# Lokalizace a časová zóna
LANGUAGE_CODE = "en-us"
ADMIN_LANGUAGE_CODE = "en-us"
TIME_ZONE = 'Europe/Prague'
USE_I18N = True
USE_L10N = True
USE_TZ = False

# Statické soubory
STATIC_URL = 'static/'

# Výchozí primární klíč
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#️ E-mailové nastavení pro testy a vývoj
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'lucka.scholz@gmail.com'
FRONTEND_URL = 'http://localhost:3000'