# Generated by Django 4.2.19 on 2025-02-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_alter_position_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='group',
        ),
    ]
