# Generated by Django 4.2.19 on 2025-02-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_warehouse_location_warehouse_address_and_more'),
        ('position', '0004_remove_position_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='warehouse',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
            preserve_default=False,
        ),
    ]
