# Generated by Django 4.2.18 on 2025-02-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ManyToManyField(related_name='users', to='client.client'),
        ),
    ]
